### ISSUE TITLE
Unable installation of other instances

### ISSUE THREAD

**Issue by SvenScherf** [Bill-Stewart/ApacheTomcatSetup#4]
By the installation with a differnd service name as tomcat you cannot start the Apache service.

Now i install with the following parameters.

/instance="123" /instancename="tomcat-123"  /servicename="tomcat-123" /servicedisplayname="Apache Tomcat 9.0 tomcat-123" /dir="L:\ProgramFiles\Tomcat-9.0\tomcat-123" /type=default /tasks="installservice/setautostart,installservice,installservice/setpermissions,installservice/startmonitoratlogon" 

I get the service with the name tomcat-123 and the same displayname = fine

When i will start the service i get the error "cannot start the service" and the error number 1068.

In the directory L:\ProgramFiles\Tomcat-9.0\tomcat-123 i must rename the files
tomcat.exe -> tomcat-123.exe 
tomcatw.exe -> tomcat-123w.exe

Thanks and best regards
Sven

**Comment by Bill-Stewart** [comment]
Your parameter name `/instancename` should be `/instance` - see [documentation](https://github.com/Bill-Stewart/ApacheTomcatSetup#installing-separate-instances). This is a documentation error. The next version will support `/instance` and `/instancename`. Sorry for the confusion.

**Comment by Bill-Stewart** [comment]
Installer now supports both `/instancename` and `/instance` parameters.
